### ISSUE TITLE
[QUESTION} NUMA resources

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/dask-cuda#552]
We're trying to optimize a dask-cudf job for NUMA: DGX with multiple storage controllers -> 4 NUMA nodes -> 8 GPUs. For predictability, we're trying to tag workers with resources like:

```
environment:
  - CUDA_VISIBILE_DEVICES=3
cmd: dask-cuda-worker --resources "GPU=1 GPU3=1 NUMA5=1 "
```

In turn, that would let us color dask subgraphs by NUMA info: 

```
tasks = []
for node in [1,3,5,7]:
  with dask.annotate(resources={f'NUMA{node}': 2}):
    tasks.append(...)
wait(...)
```

However, we're seeing errors around initializing `dask-cuda-worker` wrt multiple resources. Is there a known happy path / example here? I can work to provide a repro, but have tried a few syntaxes + passing in via env vars, and no go, and was going to try starting via python next...

**Comment by lmeyerov** [comment]
For posterity commas + explicit args for `docker-compose.yml`:

```yml
  dask-cuda-worker0:
    <<: *worker_opts
    environment:
      - CUDA_VISIBLE_DEVICES=0
    command: ["dask-cuda-worker", "--interface", "eth0", "--no-dashboard", "--dashboard-address", "dask-cuda-worker0:8787", "--resources", "GPU=1,GPU0=1,NUMA3=1", "dask-scheduler:8786"]
```

Otherwise, looks like docker was eating the quotes, confusing the dask's CLI parsing
