### ISSUE TITLE
[FEA] Document how to use dask-cuda with Kubernetes

### ISSUE THREAD

**Issue by randerzander** [rapidsai/dask-cuda#63]
dask-cuda's LocalCUDACluster Python API and dask-cuda-worker CLI utility are easy to use when manually starting clusters.

The natural question arises, how would I use this with Kubernetes?

The answer could be dask-cuda is not necessary.. that users should:
1. Specify, in a kubernetes config somehow, that each container should be allocated only one GPU
2. The app should instantiate a "plain" Dask (non dask-cuda) cluster
3. `import dask_cudf`, use it, and everything works as if you're running from a dask-cuda-worker spawned cluster

That would be a fine answer.

However, dask-cuda, or dask-cudf, or cudf, or other RAPIDS project should have a step by step guide for how to set that up, and point back to relevant Kubernetes documentation for additional options.

Is there someone well qualified to write such a document soon?

**Comment by mrocklin** [comment]
> That would be a fine answer.

Yup, that sounds like the first answer that I would recommend.  I think that the right thing to do here is to add a bit of config to the worker template yaml config file that specifies that you want a GPU per pod.  

@beberg has been threatening to write up docs for this for a while now.  Barring that, this example from the Kubernetes docs might be helpful: https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

I don't personally know people who do this regularly.  However I suspect that some folks in the Pangeo collaboration (probably the most active Dask-on-Kubernetes community that is also open) might have some suggestions.  

If I were doing this I would try the config entry above on a Kubernetes cluster and fool around for a while, using that to write down a best practices document.  @quasiben might be able to help here.

**Comment by mrocklin** [comment]
To be explicit.  Today I would use either the helm chart, or dask-kubernetes, depending on how you want to use Dask on your Kubernetes system.  Docs explaining this choice are here: 

After that, you'll need to configure your worker containers to include a request for GPUs.  I don't have any practical experience here, but I think it's adding the bit of yaml from the kubernetes doc linked in the previous comment.  An example of a worker spec config file can be seen on the front page of http://kubernetes.dask.org/en/latest/ , look for "resources".

**Comment by randerzander** [comment]
Just leaving some notes here others might find useful if they start down a similar path before we've finished/published our own docs:

Per [Kubernetes docs](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/), asking for only one GPU per container can be accomplished using `kubectl` with the following yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: cuda-vector-add
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      # https://github.com/kubernetes/kubernetes/blob/v1.7.11/test/images/nvidia-cuda/Dockerfile
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
```
